/* Arrow training templates: for every intent, example messages in English (en), Telugu (te)
   and Hindi (hi), both written in English letters.
   Slots: {F} a food with an amount, {FS} one to three foods, {Fn} a bare food name, {M} a meal,
   {N} a number, {K} calories, {P} protein, {X} an exercise, {T} an app page, {SH} a shadow,
   {I}/{IS} kitchen ingredients, {ST} a stat, {D} a drink, {G} a goal, {U} a dish Arrow has never seen.
   (a|b) picks one option, [x] is optional. */
module.exports={
log_food:{n:3600,
en:['{FS}','{F}','had {FS}','i had {FS}','i ate {FS}','ate {FS}','just had {FS}','just ate {FS}','i just finished {FS}','{FS} for {M}','for {M} i had {FS}',
  'for {M} {FS}','{M}: {FS}','{M} - {FS}','{M} was {FS}','my {M} was {FS}','had {FS} for {M}','ate {FS} for {M}','i had {FS} in the (morning|afternoon|evening)',
  'today i ate {FS}','today i had {FS} for {M} and {FS} for {M}','{M} {FS}, {M} {FS}','i\'m eating {FS}','eating {FS} (now|rn|right now)','having {FS} for {M}',
  'drank {D}','i drank {N} glasses of water','{N} glasses of water','had {N} (glass|glasses|cups) of {D}','log {FS}','add {FS}','add {FS} to {M}','put {FS} in my log',
  'had a (huge|small|big|light) {M}: {FS}','{FS} after (the gym|workout|training)','post workout {FS}','pre workout {FS}','had {FS} with {FS}','{F} and {F}',
  'grabbed {FS}','snacked on {FS}','i had {U}','ate some {U}','{U} for {M}','had {U} and {F}','my mom made {U}','tried {U} today','{M} was {U}',
  'just had my {M}, {FS}','{F} {F}','{F}, {F}, {F}','i ate {F} at (the office|home|a party|my friend\'s place)','finished {FS} (just now|a while ago)',
  'had {FS} earlier','{FS} earlier today','{M} done: {FS}','{FS} (yum|was good|was tasty)','ate {N} {Fn}','{N} {Fn} for {M}','i had {N} {Fn} and {FS}',
  'water {N} glasses','(had|drank) a (glass|bottle) of water','i had {FS} at night','late night {FS}','midnight snack {FS}'],
te:['{FS} tinna','{FS} tinnanu','nenu {FS} tinnanu','{M} lo {FS} tinna','{M} ki {FS} tinna','{M} ki {FS}','ivala {M} lo {FS} tinna','{FS} tinesa','{FS} tinesanu',
  'ippude {FS} tinna','{FS} tintunna','ivala {FS} tinna','{M} {FS}','{FS} {M} lo tinna','{F} tho {F} tinna','{F} mariyu {F} tinna','{F} inka {F} tinna',
  '{D} taaganu','{N} glass neellu taaganu','{N} glasses neellu','neellu {N} glass taaganu','{D} tagaanu','nenu {U} tinna','{M} lo {U} tinna','{U} tinna',
  'amma {U} chesindi tinna','{FS} tinnanu ra','{M} ki {F} mariyu {F}','gym tarvata {FS} tinna','workout ki mundu {FS} tinna','{N} {Fn} tinna','{Fn} {N} tinna'],
hi:['{FS} khaya','{FS} khayi','{FS} khaye','maine {FS} khaya','maine {FS} khaye','aaj {M} mein {FS} khaya','{M} mein {FS}','{M} mein {FS} khaya','{FS} kha liya',
  'abhi {FS} kha raha hoon','abhi {FS} khaya','{F} aur {F} khaya','{F} ke saath {F}','{D} piya','{N} glass paani piya','paani piya {N} glass','{D} pi liya',
  'maine {U} khaya','{M} mein {U}','mummy ne {U} banaya tha wahi khaya','{FS} khaya yaar','gym ke baad {FS} khaya','workout se pehle {FS} khaya','{N} {Fn} khaye',
  'aaj {FS} khaya','{M} ko {FS} khaya']},
food_info:{n:1500,
en:['how many calories in {F}','how many calories in {Fn}','calories in {Fn}?','calories of {F}','how much protein in {Fn}','how much protein does {Fn} have',
  'protein in {F}?','what are the macros of {Fn}','macros for {F}','is {Fn} healthy','is {Fn} high in protein','is {Fn} good for bulking','is {Fn} fattening',
  'how many carbs in {Fn}','how much fat in {Fn}','does {Fn} have (protein|sugar|fiber)','nutrition of {Fn}','{Fn} nutrition','{Fn} calories?','kcal in {F}',
  'how much sugar is in {Fn}','tell me about {Fn} nutrition','what is the protein in {N} {Fn}','how many calories are in {N} {Fn}','{Fn} vs {Fn} which has more protein',
  'is {Fn} good after workout','can i eat {Fn} on a cut','how many calories would {F} be','if i eat {F} how many calories'],
te:['{Fn} lo entha protein untundi','{Fn} lo calories entha','{Fn} lo entha calories','{F} ki entha calories','{Fn} healthy na','{Fn} lo protein unda',
  '{Fn} tinte bulk avtama','{Fn} manchidena','{Fn} lo sugar entha'],
hi:['{Fn} mein kitni calories hoti hai','{Fn} mein kitna protein hai','{F} mein kitni calories','{Fn} healthy hai kya','{Fn} mein protein hota hai kya',
  '{Fn} khane se weight badhta hai kya','{Fn} ki calories batao','{Fn} mein kitni sugar hai']},
undo:{n:900,
en:['undo','undo that','undo last','undo the last one','oops undo','oops remove that','remove that','delete that','delete the last (one|entry|thing|log)',
  'remove the last (one|entry|item|log)','take that back','that was wrong','wrong entry','scratch that','cancel that','cancel the last log','nvm remove it',
  'i didn\'t eat that, remove it','that was a mistake','go back','revert that','erase the last one','remove what i just added','delete my last message food'],
te:['adi teeseyi','adi delete cheyyi','last di teeseyi','pichadi teeseyi','tappu ayindi teeseyi','adi cancel cheyyi','undo cheyyi','vaddu adi teeseyi'],
hi:['woh hata do','last wala hata do','galti se add hua hata do','undo karo','woh delete karo','cancel karo woh','galat hai hatao']},
remove_item:{n:1100,
en:['wait i didn\'t (actually )?(have|eat) the {Fn}, (remove|delete) (it|them|that|those)','i didn\'t eat the {Fn} (my (brother|friend|sister) ate it|it was someone else\'s), delete it','the {Fn} was a mistake, remove it','scratch the {Fn}','{Fn} wasn\'t mine, take it off','remove the {N} {Fn} from {M}','delete those {Fn}','take the {Fn} off today\'s list','remove {Fn}','remove the {Fn}','delete {Fn}','delete the {Fn} (entry|log)','take out the {Fn}','remove {Fn} from today','remove {Fn} from {M}',
  'i didn\'t have the {Fn}, remove it','delete {Fn} from my log','remove the {Fn} i logged','get rid of the {Fn} entry','take {Fn} off my log'],
te:['{Fn} nenu tinaledu adi teeseyi','{M} lo {Fn} teeseyi tinaledu','{Fn} list nunchi teeseyi','{Fn} teeseyi','{Fn} delete cheyyi','{Fn} remove cheyyi','{M} lo {Fn} teeseyi'],
hi:['{Fn} maine nahi khaya hata do','{Fn} galti se add hua hatao','{M} wala {Fn} hata do','{Fn} hata do','{Fn} delete karo','{Fn} list se hatao','{Fn} nikal do']},
correction:{n:900,
en:['{Fn} is {K}','{F} is {K}','{Fn} = {K}','{F} = {K}','{Fn} has {K}','{Fn} has {K} and {P}','{F} is about {K}','actually {Fn} is {K}',
  'my {Fn} is {K} each','{Fn} is around {K}','{Fn} is {K} not that much','correct {Fn} to {K}','set {Fn} to {K}','{Fn} should be {K}','change {Fn} calories to {K}',
  '{Fn} is {K} with {P}'],
te:['{Fn} {K} untundi','{Fn} ki {K}','{Fn} {K} ani pettu'],
hi:['{Fn} {K} hai','{Fn} mein {K} hai','{Fn} ki calories {K} kar do']},
summary:{n:1000,
en:['how am i doing','how am i doing today','summary','today\'s summary','give me a summary','show my summary','what\'s my total','total so far','how much have i eaten',
  'how many calories have i eaten (today|so far)','how much protein did i (get|eat|have) today','status','status check','what\'s left for today','how much is left',
  'how many calories left','remaining calories','am i on track','did i hit my protein','how much water have i had','progress on food today','where am i at',
  'day summary','report please','calories so far?'],
te:['ivala entha tinnanu','ivala entha protein tinna','inka entha tinali','summary cheppu','ivala total entha','naa progress enti ivala','entha migilindi'],
hi:['aaj kitna khaya','aaj kitna protein hua','abhi tak kitni calories hui','summary batao','kitna bacha hai','aaj ka total kya hai','kaisa chal raha hai aaj']},
targets:{n:800,
en:['what\'s my (target|goal)','what\'s my calorie (target|goal)','how many calories should i eat','how much protein should i eat','how much protein do i need',
  'what are my macros','what are my targets','daily target?','how much water should i drink','my daily goals','what\'s my protein target','how many carbs should i eat',
  'what should my calories be','how much fiber do i need','what is my limit for sugar'],
te:['naa target entha','roju entha protein tinali','entha calories tinali','naa goal enti','roju entha neellu taagali'],
hi:['mera target kya hai','mera daily goal kya hai','kitna protein khana chahiye','kitni calories khani chahiye','roz kitna paani peena chahiye']},
set_goal:{n:800,
en:['i want to {G}','switch [me ]to {G}','change my goal to {G}','set my goal to {G}','my goal is {G}','i wanna {G}','i\'m trying to {G}','let\'s {G}',
  'start a {G}','put me on a {G}','goal {G}','i want to (lose|gain) weight','i want to get (lean|bigger|shredded)','help me {G}'],
te:['nenu {G} cheyali','weight taggali','weight perugali','bulk avvali','cut cheyali','goal {G} ki maarchu'],
hi:['mujhe {G} karna hai','weight kam karna hai','weight badhana hai','mujhe bulk karna hai','goal {G} kar do']},
suggest_meal:{n:1300,
en:['what should i eat','what should i eat for {M}','what should i have for {M}','what to eat','suggest a meal','suggest something for {M}','suggest something high protein',
  'i\'m hungry','i\'m starving','im hungry what do i eat','give me a {M} idea','meal ideas','what can i eat (now|tonight)','what\'s good for {M}',
  'what should i eat before (my )?workout','what to eat after (my )?workout','post workout meal ideas','pre workout snack ideas','give me a snack idea',
  'any food suggestions','recommend something to eat','what\'s a good late night snack','high protein snack ideas','what should i eat to hit my protein',
  'i need more protein what should i eat','i need protein','suggest dinner','cheap high protein food','quick breakfast ideas'],
te:['emi tinali','emi tinali ippudu','{M} ki emi tinali','aakali ga undi','aakaliga undi emaina cheppu','workout tarvata emi tinali','gym ki mundu emi tinali',
  'protein kosam emi tinali','emaina suggest cheyyi'],
hi:['kya khaun','kya khaun abhi','{M} mein kya khaun','bhookh lagi hai','bahut bhookh lagi hai','kuch suggest karo khane ko','workout ke baad kya khaun',
  'gym se pehle kya khaun','protein ke liye kya khaun']},
repeat_meal:{n:800,
en:['same as yesterday','same {M} as yesterday','same as yesterday\'s {M}','the usual','my usual','log my usual','log my usual {M}','usual {M}','same as usual',
  'same {M} as always','repeat yesterday','repeat yesterday\'s {M}','copy yesterday','i ate the same as yesterday','same thing as yesterday for {M}',
  'had my usual {M}','the usual please','same old {M}'],
te:['ninna laage tinna','ninna tinnade tinna','eppudu tinnade','roju tinedi','ninna {M} laage','same ninna laage'],
hi:['kal jaisa hi khaya','kal wala hi','roz wala {M}','wahi jo roz khata hoon','kal jaisa {M}']},
skipped_meal:{n:800,
en:['i skipped {M}','skipped {M}','didn\'t eat anything','i didn\'t eat (today|yet)','no {M} today','i haven\'t eaten (yet|anything)','nothing today','i ate nothing',
  'didn\'t have {M}','i\'m fasting','fasting today','i missed {M}','had nothing for {M}','no food yet','i forgot to eat','didn\'t get time to eat {M}'],
te:['emi tinaledu','ivala emi tinaledu','{M} tinaledu','{M} ledu','{M} skip chesa','inka emi tinaledu','upavasam'],
hi:['kuch nahi khaya','aaj kuch nahi khaya','{M} nahi kiya','{M} skip kiya','abhi tak kuch nahi khaya','vrat hai aaj']},
dont_know:{n:700,
en:['i don\'t know what i ate','i don\'t know what i eat','i don\'t know','idk what i ate','can\'t remember what i had','i forgot what i ate','no idea what i ate',
  'not sure what i had','not sure what was in it','no idea how much i ate','i don\'t remember','don\'t know the quantity','idk the amount','i\'m not sure'],
te:['gurtu ledu','emi tinnano gurtu ledu','teliyadu','entha tinnano teliyadu','naaku teliyadu'],
hi:['pata nahi','pata nahi kya khaya','yaad nahi','kitna khaya pata nahi','mujhe nahi pata']},
kitchen_add:{n:900,
en:['i have {IS} at home','i have {IS} in my (kitchen|fridge)','we have {IS}','there\'s {IS} in the fridge','bought {IS}','i bought {IS}','got {IS} from the store',
  'add {IS} to my kitchen','add {IS} to the pantry','my fridge has {IS}','kitchen has {IS}','stocked up on {IS}','i\'ve got {IS} at home','{IS} are in my kitchen',
  'available at home: {IS}','groceries: {IS}'],
te:['intlo {IS} unnayi','fridge lo {IS} undi','{IS} konna','intlo {IS} undi','kitchen lo {IS} unnayi'],
hi:['ghar mein {IS} hai','fridge mein {IS} hai','{IS} le aaya','ghar pe {IS} hai','kitchen mein {IS} rakha hai']},
kitchen_remove:{n:700,
en:['out of {I}','i\'m out of {I}','no more {I}','{I} is finished','{I} finished','we ran out of {I}','used up the {I}','remove {I} from my kitchen',
  'remove {I} from the pantry','{I} is over','{I} got over','delete {I} from kitchen'],
te:['{I} ayipoyindi','{I} ayipoyayi','{I} ledu intlo','{I} kitchen nunchi teeseyi'],
hi:['{I} khatam ho gaya','{I} khatam','{I} nahi hai ab','{I} kitchen se hatao']},
kitchen_show:{n:700,
en:['show me what\'s (already )?in my kitchen','before i go shopping show my kitchen','can you show what\'s in my kitchen so i don\'t buy double','what do i already have at home','list what\'s in my fridge','do i have {I} at home?','is there {I} in my kitchen','what\'s in my kitchen','show my kitchen','show my pantry','what ingredients do i have','what do i have at home','list my kitchen','what\'s in the fridge',
  'my pantry list','kitchen list'],
te:['intlo emi items unnayo chupinchu','kitchen lo emi undo chupinchu','naa kitchen list chupinchu','intlo {I} unda','intlo emi unnayi','kitchen lo emi unnayi','fridge lo emi undi'],
hi:['ghar mein kya kya hai dikhao','kitchen list dikhao','ghar mein {I} hai kya','ghar mein kya hai','kitchen mein kya kya hai','fridge mein kya hai']},
kitchen_cook:{n:800,
en:['what can i cook','what can i make','what can i cook with {IS}','what can i make with {IS}','recipe with what i have','cook something with {IS}',
  'what should i cook','what should i make for {M}','give me a recipe with {IS}','i have {IS} what can i cook','any recipe using {IS}','what can i cook right now',
  'recipe ideas from my kitchen'],
te:['emi vandali','emi vandukovali','{IS} tho emi vandali','{M} ki emi vandali','intlo unna vaatitho emi cheyochu'],
hi:['kya banau','kya banau aaj','{IS} se kya banau','{M} mein kya banau','ghar mein jo hai usse kya bana sakta hoon']},
reset_log:{n:600,
en:['reset today\'s (food )?log','reset today','clear today\'s (food )?log','delete everything i ate today','delete all food entries','clear all food entries',
  'start today\'s log over','wipe today\'s food','remove all meals today','reset my food log','clear my log for today'],
te:['ivala log motham teeseyi','ivala tinnavi anni delete cheyyi'],
hi:['aaj ka sab hata do','aaj ka log reset karo','aaj ka khana sab delete karo']},
clear_chat:{n:700,
en:['clear the chat','clear the chat please','clear chat','delete all messages','delete the messages','wipe the chat','wipe this conversation','clear conversation',
  'start a new chat','new chat','erase the chat','clean the chat','clear our messages','delete chat history','clear history of chat','reset the chat'],
te:['chat clear cheyyi','chat delete cheyyi','messages anni teeseyi','kotha chat start cheyyi'],
hi:['chat saaf karo','chat clear karo','saare messages delete karo','nayi chat shuru karo']},
greet:{n:800,
en:['hi','hello','hey','hey arrow','hi arrow','hello arrow','yo','sup','hii','heyy','good morning','good afternoon','good evening','morning','hey there','hi there',
  'hola','hey bro','helo','hiya','gm','wassup arrow'],
te:['namaskaram','hi ra','hello anna','emandi','hey ra'],
hi:['namaste','namaskar','hello ji','hi yaar','ram ram']},
bye:{n:600,
en:['bye','goodbye','bye arrow','see you','see you later','see ya','good night','gn','night arrow','ok i\'m done','that\'s all for now','talk later','later',
  'i\'m going to sleep','going to bed','ttyl','catch you later','done for today'],
te:['bye ra','malli kaluddam','padukuntunna','good night ra','vellostha'],
hi:['chalo bye','phir milte hain','sone ja raha hoon','alvida','shubh ratri','tata']},
thanks:{n:800,
en:['thanks (bro|man) (seriously|really), (that helped a lot|you\'re a lifesaver|that finally makes sense)','thank you, i was so confused about {Fn} and now it makes sense','thanks that was helpful','thank you for explaining','appreciate the help','thanks for the tip','thanks for reminding me','thanks','thank you','thanks arrow','thank you so much','thx','ty','thanks a lot','tysm','thanks bro','appreciate it','cheers','thanks buddy','many thanks','thanks bot',
  'thank you bot','thank you arrow','thanks for the help','thanks for logging that','thank u','tq','thanks man','okay thanks','thanks a ton'],
te:['chala thanks ra ardham ayindi','thanks anna help chesav','thanks ra','dhanyavadalu','thanks anna','chala thanks'],
hi:['shukriya samajh aa gaya','thanks yaar bahut help hui','dhanyavaad','shukriya','thanks yaar','bahut shukriya','thank you bhai']},
praise:{n:750,
en:['you\'re goated','ur goated','arrow is goated','you\'re the goat','you\'re fire','this is fire','you\'re lit','op bot','legend','you\'re a legend','absolute legend','you\'re so smart','i love you arrow','10/10 bot','you\'re better than chatgpt','you\'re awesome','good bot','nice work','great job arrow','you\'re smart','you\'re the best','love you arrow','i love this bot','you\'re amazing','well done',
  'impressive','you\'re actually helpful','you\'re cute','nice one','you\'re so cool','best bot ever','you rock'],
te:['nuvvu keka ra','super ga chepthunnav','nuvvu baga chestunnav','nuvvu super','chala baagunnav','keka arrow','nuvvu thopu'],
hi:['tum toh legend ho','kya baat hai arrow','ekdum mast ho tum','tum best ho','bahut badhiya','kamaal ho tum','zabardast','tum toh kamaal ho']},
insult:{n:700,
en:['you don\'t know anything','you know nothing','you\'re clueless','useless piece of code','you\'re the worst','you\'re so slow','you got that wrong again idiot','you\'re useless','stupid bot','you\'re dumb','you\'re so dumb','worst bot ever','you suck','this app sucks','idiot','shut up','you\'re annoying','you\'re wrong again',
  'you never understand me','dumb ai','you\'re trash'],
te:['neeku emi teliyadu','neeku em ardham kaadu','nuvvu dumb','pichi bot neeku emi teliyadu','nee valla em use ledu','nuvvu waste','pichi bot','em artham kaadu neeku','nuvvu panikiraavu'],
hi:['tumhe kuch nahi pata','tum bekaar ho yaar','kuch nahi aata tumhe','bewakoof bot','tum bekar ho','pagal bot','tumhe kuch samajh nahi aata','bakwas app','chup raho']},
how_are_you:{n:500,
en:['how are you','how are you doing','how\'s it going','what\'s up','sup arrow how are you','how you doing','how have you been','you good?','how\'s your day',
  'how are things'],
te:['ela unnav','ela unnaru','em chestunnav','antha ok na'],
hi:['kaise ho','kya haal hai','kaisa chal raha hai','sab theek','kya chal raha hai']},
who_are_you:{n:700,
en:['are you a bot or a real person','is someone typing these','are you real','is this a real person','why are you called arrow','why is your name arrow','is arrow from the anime','are you chatgpt','what kind of bot are you','who programmed you','who are you','what are you','what\'s your name','what is your name','are you a robot','are you human','are you an ai','who made you','who built you',
  'introduce yourself','tell me about yourself','what is arrow'],
te:['nuvvu nijamga manishi va','ninnu arrow ani enduku pilustaru','nuvvu evaru','nee peru enti','nuvvu robot aa','ninnu evaru chesaru'],
hi:['tum insaan ho ya bot','tumhara naam arrow kyun hai','tum kaun ho','tumhara naam kya hai','kya tum robot ho','tumhe kisne banaya']},
help:{n:600,
en:['help','help me','what can you do','how do i use you','how does this work','what are your features','commands','show commands','what can i ask you',
  'what can i say','how to use arrow','what do you do','guide me','instructions'],
te:['nuvvu emi cheyagalav','ela vaadali ninnu','help cheyyi'],
hi:['tum kya kar sakte ho','kaise use karu','madad karo','help karo']},
joke:{n:500,
en:['tell me a joke','joke please','make me laugh','say something funny','got any jokes','tell a gym joke','another joke','cheer me up with a joke','roast me'],
te:['oka joke cheppu','navvinchu','joke cheppu ra'],
hi:['ek joke sunao','joke sunao','hasao mujhe','kuch funny bolo']},
laugh:{n:500,
en:['lol','haha','hahaha','lmao','rofl','hehe','lol 😂','😂','😂😂','🤣','lolll','haha nice','that\'s funny','xd','lmaooo'],
te:['hahaha ra','navvu vastundi'],
hi:['hahaha yaar','bahut funny']},
affirm:{n:600,
en:['yes','yeah','yep','yup','sure','ok','okay','ok do it','yes please','go ahead','do it','sounds good','correct','right','absolutely','of course','yeah sure','fine'],
te:['avunu','sare','ok ra','haa','cheyyi'],
hi:['haan','haan ji','theek hai','bilkul','kar do','chalega']},
deny:{n:600,
en:['no','nope','nah','no thanks','don\'t','not now','never mind','nvm','no way','cancel','stop','leave it','no no','don\'t do that'],
te:['vaddu','ledu','vaddu ra','akkarledu'],
hi:['nahi','nahin','rehne do','mat karo','nahi chahiye']},
out_of_scope:{n:1900,
en:['did you watch {MV}','is {MV} worth watching','who won ipl','what\'s the score','recommend a web series','what should i name my dog','i need a haircut','what\'s the weather (today|tomorrow)','who won the match yesterday','write my homework','what\'s {N} times {N}','play a song','book a cab','what is the capital of (france|india|japan)',
  'my phone is lagging','tell me the news','who is the prime minister','how to make money online','recommend a movie','what time is it','set an alarm',
  'call my mom','translate this to french','how do i fix my laptop','what is love','do you like cricket','who is virat kohli','i like cars','my exam is tomorrow',
  'how to code in python','order pizza online','what\'s bitcoin price','tell me a story','sing a song','how far is the moon','what day is it','is it going to rain',
  'help me with maths','who is the best actor','send a message to my friend','open youtube','how to get a girlfriend','my boss is angry','asdfgh','hmm','ok so',
  'what','random','blah blah','test','testing 123','can you hear me','i am bored','buy me a phone','what is the meaning of life','how old are you'],
te:['{MV} cinema chusava','{MV} chusava ra','{MV} ela undi','ipl lo evaru gelicharu','match chusava','exam results eppudu','bike service ki ivvali','cinema ki veldama','exam ela undi','bus late ayindi','repu college undi','ee movie ela undi','cricket score enti','weather ela undi','phone charge ledu'],
hi:['{MV} dekhi kya','{MV} kaisi thi','ipl kaun jeeta','match dekha kya','result kab aayega','bike ki service karani hai','kal movie dekhne chalein','exam kaisa gaya','bus late ho gayi','aaj mausam kaisa hai','cricket score kya hai','kal college jaana hai','phone ki battery khatam']},
ask_streak:{n:600,
en:['what\'s my streak','my streak?','how many days in a row','how long is my streak','is my streak still alive','did i break my streak','what\'s my best streak',
  'how many days have i trained in a row','streak status','current streak'],
te:['naa streak entha','streak inka undha','enni rojulu continuous ga chesa'],
hi:['meri streak kitni hai','streak tooti kya','lagatar kitne din kiya']},
ask_level:{n:700,
en:['what level am i','my level?','what\'s my rank','what rank am i','how much exp do i have','how much xp do i have','how close am i to level up',
  'when do i level up','exp to next level','what\'s my hunter rank','am i {R} rank','show my level','level status'],
te:['naa level entha','naa rank enti','inka entha exp kavali'],
hi:['mera level kya hai','mera rank kya hai','kitna exp hai','level up kab hoga']},
ask_quest:{n:900,
en:['what\'s my workout today','what is today\'s quest','today\'s quest?','what\'s the quest today','what exercises today','how many {X} today','how many {X} do i have to do today',
  'what do i train today','is today a rest day','did i finish today\'s quest','is my quest done','how much of the quest is left','what\'s left in my workout',
  'today\'s workout plan','which day is it today push or pull','what\'s on the schedule today','do i have to work out today'],
te:['ivala workout enti','ivala quest enti','ivala rest day aa','ivala enni {X} cheyali','quest ayipoyinda'],
hi:['aaj ka workout kya hai','aaj ka quest kya hai','aaj rest day hai kya','aaj kitne {X} karne hain','quest ho gaya kya']},
ask_records:{n:600,
en:['what\'s my best {X}','my {X} record','show my personal records','what are my prs','my pr for {X}','max {X} i did','my best plank time','personal best?',
  'what\'s my record','highest reps i did','my best ever {X}'],
te:['naa best {X} entha','naa record enti'],
hi:['mera best {X} kitna hai','mera record kya hai']},
ask_shadows:{n:700,
en:['who is my strongest shadow','how many shadows do i have','who\'s my captain','who is my vice captain','what level is {SH}','how strong is {SH}','tell me about {SH}',
  'what are my shadows','my shadow army?','which shadow is the best','what does {SH} do','shadow bonuses?','what skills do my shadows give'],
te:['naa shadows enni','strongest shadow evaru','captain evaru','{SH} level entha'],
hi:['mere kitne shadows hain','sabse strong shadow kaun hai','captain kaun hai','{SH} ka level kya hai']},
ask_next_rank:{n:750,
en:['how much more (xp|exp) till {R} rank','(xp|exp) needed for {R} rank','how far am i from {R} rank','what do i need to reach {R} rank','when will i become {R} rank','how long until my next rank','when can i rank up','what do i need for the next rank','when is my next trial','next rank?','how to reach {R} rank','how far is the next rank',
  'can i take the rank trial','rank up requirements','when do i become {R} rank'],
te:['{R} rank ki inka entha exp kavali','next rank eppudu vastundi','next rank ki entha undi','rank up eppudu','trial eppudu'],
hi:['{R} rank ke liye kitna exp chahiye','agla rank kab aayega','next rank kab milega','rank up kaise karu','trial kab hai']},
ask_stats:{n:600,
en:['what are my stats','show my stats','how much {ST} do i have','my {ST} stat','what\'s my {ST}','do i have stat points','unspent points?','which stat is highest',
  'my attributes','stat points to spend'],
te:['naa stats enti','naa {ST} entha'],
hi:['mere stats kya hain','mera {ST} kitna hai']},
ask_items:{n:750,
en:['any potions left?','potions?','do i still have (keys|potions|boxes|an elixir)','how many (elixirs|potions|boxes|keys) left','what items do i have','got any keys?','keys left?','how many keys do i have','what\'s in my inventory','show my inventory','which weapon do i have equipped','what weapon am i using','do i have any potions',
  'how many boxes do i have','my items','do i have an elixir','what titles do i have','my weapons?','do i have gate keys'],
te:['naa daggara potions unnaya','inventory lo enni boxes unnayi','elixir unda','naa daggara enni keys unnayi','naa inventory enti','naa weapon enti'],
hi:['potion bacha hai kya','kitne boxes hain','elixir hai kya','mere paas kitni keys hain','mera inventory dikhao','mera weapon kaunsa hai']},
ask_week:{n:600,
en:['how was my week','how many workouts this week','weekly progress','how many days did i train this week','total reps so far','how many quests have i done',
  'how many gates have i cleared','my weekly report','this week\'s summary','how consistent was i this week'],
te:['ee week ela undi','ee week enni rojulu chesa'],
hi:['is hafte kaisa raha','is baar kitne din workout kiya','is week kitne din kiya']},
exercise_howto:{n:1200,
en:['my hips (keep )?sagging in (the )?{X}, what am i doing wrong','what am i doing wrong with my {X} form','my {X} form is bad','elbows flare in my {X}','is my {X} form right','fix my {X} form','common {X} mistakes','how to do a {X} without equipment','how to (start|learn) {X}','how do i do a {X}','how to do {X}','how to do {X} properly','{X} form','{X} form tips','show me how to do {X}','what\'s the right way to do {X}',
  'teach me {X}','how should i do {X}','correct form for {X}','{X} technique','explain {X}','i can\'t do {X} properly','{X} tutorial'],
te:['{X} lo form correct ga unda','{X} chesetappudu enti tappu','{X} ela nerchukovali','{X} ela cheyali','{X} ela chestaru','{X} correct ga ela','{X} nerpinchu'],
hi:['{X} mein form kaise sahi kare','{X} karte waqt kya galti hoti hai','{X} kaise seekhe','{X} kaise karte hain','{X} kaise kare','{X} ka sahi tarika','{X} sikhao']},
motivate:{n:800,
en:['i don\'t feel like working out','motivate me','i\'m so lazy [today]','i\'m lazy','give me motivation','i want to give up','i can\'t do this','i\'m tired of this',
  'no motivation today','push me','hype me up','i don\'t want to train','skip workout today?','i feel like quitting','i\'m not feeling it today','convince me to work out'],
te:['badhakam ga undi','workout cheyalani ledu','motivate cheyyi','naaku opika ledu','vadileyalani undi'],
hi:['mann nahi kar raha','aalas aa raha hai','motivate karo','workout ka mood nahi hai','chhod du kya']},
recovery:{n:850,
en:['how many rest days do i need (in a week)?','should i take (a )?rest (day )?today','i\'m (so|really) tired, should i skip today','is it ok to rest today','do i need a rest day','how long should i rest a sore muscle','can i train two days in a row','my legs are sore','i\'m so sore','sore muscles','should i train if i\'m sore','how to recover faster','i slept only {N} hours','i\'m exhausted should i rest',
  'should i take a rest day','body is tired','doms is killing me','how much sleep do i need','i feel weak today','muscle soreness tips'],
te:['chala alasata ga undi ivala rest teesukona','rest day kavala','body tired ga undi rest cheyyala','body pains ga unnayi','kallu noppi ga unnayi','rest teesukovala','alasata ga undi'],
hi:['bahut thak gaya hu aaj rest le lu','rest lena chahiye kya','aaj rest karu kya','body thaki hui hai','body mein dard hai','thakaan hai','muscles dukh rahe hain','rest karu kya']},
pain:{n:800,
en:['sharp pain in my {B} since yesterday','my {B} has been hurting for days','it hurts to bend my {B}','i can\'t move my {B} without pain','my {B} hurts','{B} pain','i have {B} pain','{B} hurts when i do {X}','i think i pulled a muscle','sharp pain in my {B}','i injured my {B}','my {B} is swollen',
  'it hurts when i bend','i twisted my ankle','i felt a pop in my {B}'],
te:['ninna nunchi {B} baaga noppi ga undi','{B} chala noppi','{B} noppi vangalante kashtam ga undi','{B} lo debba tagilindi','{B} vaachindi','{B} noppi ga undi','{B} lo noppi','debba tagilindi'],
hi:['kal se {B} mein bahut dard hai','{B} mein tez dard','{B} sooj gaya hai','jhukne mein dard hota hai','{B} mein dard hai','{B} dukh raha hai','chot lag gayi']},
coach_tip:{n:900,
en:['how do i grow my {BP}','how to get a bigger {BP}','best way to build {BP}','{BP} workout tips','how to make my {BP} stronger','how do i get abs','how to increase {X}','how to do more {X}','tips to build muscle','how to build muscle','how to get stronger','how long should i rest between sets',
  'how to get bigger arms','how to lose belly fat','how to get a six pack','how many sets should i do','how to improve stamina','how to get faster',
  'how to improve flexibility','is cardio needed','how to break a plateau'],
te:['{BP} pedda avvali ante emi cheyali','{BP} ela penchali','{BP} strong avvalante emi cheyali','abs ela vastayi','muscle ela penchali','stamina ela penchali'],
hi:['{BP} bade kaise kare','{BP} kaise banaye','{BP} strong kaise kare','abs kaise banaye','muscle kaise banaye','stamina kaise badhaye','pet kaise kam kare']},
open_tab:{n:1000,
en:['go to {T}','open {T}','show me {T}','show me the {T} page','take me to {T}','open the {T} tab','switch to {T}','{T} page','go to the {T} screen',
  'show my shadows','open my army','open the armory','show my weapons','show my grocery list','open history','show my feats','open my weekly report','go home'],
te:['{T} open cheyyi','{T} chupinchu','{T} ki vellu'],
hi:['{T} kholo','{T} dikhao','{T} pe le chalo']},
start_workout:{n:700,
en:['start my workout','start workout','let\'s train','let\'s work out','begin today\'s quest','start the quest','start training','let\'s go','time to work out',
  'i\'m ready to train','start the daily quest','let\'s do this','begin workout','i want to work out now'],
te:['workout start cheyyi','workout modaledadam','start cheddam'],
hi:['workout shuru karo','chalo workout karte hain','quest shuru karo']},
open_license:{n:550,
en:['lemme see my license','let me see my (license|licence|lisence|card)','show me my licence','open hunter licence','my lisence','where is my license','show my hunter license','open my license','show my card','open my card','show my id','hunter card','my license please','show my id card'],
te:['naa license chupinchu','card open cheyyi'],
hi:['mera license dikhao','mera card dikhao']},
open_settings:{n:400,
en:['open settings','settings','open my profile','show profile','go to settings','preferences','change my name','app settings'],
te:['settings open cheyyi','profile chupinchu'],
hi:['settings kholo','profile dikhao']},
theme:{n:400,
en:['dark mode','light mode','switch to (dark|light) mode','turn on (dark|night|light) mode','night mode','make it dark','make it light','change theme',
  'too bright','screen is too dark'],
te:['dark mode pettu','light mode pettu'],
hi:['dark mode karo','light mode karo']}
};
