/* Hunter System: recipe book.
   Macros are per serving and are estimates from USDA FoodData Central and
   ICMR-NIN values; home cooking varies.
   Ingredient strings: "qty|unit|item|group". qty 0 = to taste.
   Groups: P produce, D dairy & eggs, G grains & bread, L pulses & soy,
           M meat & fish, N nuts & seeds, S pantry & spices. */
const GROUPS={P:'Vegetables & fruit',D:'Dairy & eggs',G:'Grains & bread',L:'Pulses & soy',M:'Meat & fish',N:'Nuts & seeds',S:'Pantry & spices'};
const COST_LABEL={1:'₹',2:'₹₹',3:'₹₹₹'};

/* R(id, name, meal, diet tag, cuisine, serving, [protein,carbs,fiber,kcal], [prep,cook] min, difficulty, cost 1-3, flags, ingredients, steps, protein tip)
   flags: 'pre' good 30-60 min before training, 'post' good after training */
const R=(id,n,meal,tag,cuisine,serv,m,t,diff,cost,flags,ing,steps,tip)=>({id,n,meal,tag,cuisine,serv,p:m[0],c:m[1],f:m[2],kcal:m[3],prep:t[0],cook:t[1],diff,cost,flags:flags?flags.split(' '):[],ing,steps,tip});

const RECIPES=[
/* ---------------- breakfast ---------------- */
R('boiled-eggs','Boiled eggs','breakfast','egg','Indian','2 eggs',[12,1,0,140],[1,10],'Easy',1,'post',
  ['2||eggs|D','0||salt|S','0||black pepper|S'],
  ['Put the eggs in a pan and cover them with cold water.','Bring to a boil, then lower the heat and simmer for 9 to 10 minutes for hard-boiled.','Move the eggs to cold water for 2 minutes so they peel easily.','Peel, halve, and sprinkle with salt and pepper.'],
  'Add a third egg white for +4g protein with almost no extra calories.'),
R('veg-poha','Vegetable poha','breakfast','veg','Indian','1 bowl (150g)',[4,38,2,180],[10,10],'Easy',1,'pre',
  ['60|g|thick poha|G','1||small onion|P','0.5|cup|peas and carrot|P','1||green chilli|P','1|tsp|mustard seeds|S','0.25|tsp|turmeric|S','1|tsp|oil|S','0.5||lemon|P','0||salt|S'],
  ['Rinse the poha in a sieve under water for 20 seconds, then let it drain.','Heat the oil, add mustard seeds, and let them splutter.','Add chopped onion, chilli, peas and carrot. Cook 4 minutes.','Add turmeric and salt, then the poha. Mix gently on low heat for 2 minutes.','Finish with lemon juice and coriander.'],
  'Stir in 2 tbsp roasted peanuts for +4g protein, or serve with a glass of milk.'),
R('oats-milk','Oats with milk','breakfast','veg','Global','40g oats + 200ml milk',[11,32,5,250],[2,5],'Easy',1,'pre',
  ['40|g|rolled oats|G','200|ml|milk|D','1||small banana|P','1|tsp|honey|S','0||cinnamon|S'],
  ['Add oats and milk to a pan.','Cook on medium heat, stirring, for 4 to 5 minutes until creamy.','Top with sliced banana, honey and a pinch of cinnamon.'],
  'Stir in 1 tbsp peanut butter or 2 tbsp curd after cooking for +4g protein.'),
R('besan-cheela','Besan cheela','breakfast','veg','Indian','2 pieces',[14,24,4,230],[10,10],'Easy',1,'',
  ['60|g|besan (gram flour)|L','1||small onion|P','1||tomato|P','1||green chilli|P','0.25|tsp|ajwain|S','1|tsp|oil|S','0||salt|S'],
  ['Whisk the besan with about 100ml water into a smooth, pourable batter.','Mix in finely chopped onion, tomato, chilli, ajwain and salt.','Heat a pan, brush with a little oil, and pour in half the batter. Spread thin.','Cook 2 minutes per side until golden. Repeat with the rest.'],
  'Crumble 40g paneer into the batter for +7g protein.'),
R('curd-banana','Curd with banana','breakfast','veg','Indian','200g curd + 1 banana',[9,24,2,210],[3,0],'Easy',1,'post',
  ['200|g|curd (dahi)|D','1||banana|P','1|tsp|honey|S'],
  ['Spoon the curd into a bowl and whisk it smooth.','Slice the banana on top.','Drizzle with honey.'],
  'Use hung curd (strained 1 hour) for nearly double the protein.'),
R('paneer-bhurji','Paneer bhurji','breakfast','veg','Indian','100g paneer',[18,4,1,265],[5,10],'Easy',2,'post',
  ['100|g|paneer|D','1||small onion|P','1||tomato|P','1||green chilli|P','0.25|tsp|turmeric|S','0.5|tsp|garam masala|S','1|tsp|oil|S','0||salt|S'],
  ['Crumble the paneer with your fingers.','Heat oil and cook chopped onion and chilli for 3 minutes.','Add tomato, turmeric and salt. Cook until soft.','Add paneer and garam masala. Stir for 2 minutes. Serve with a roti.'],
  'Already high in protein. Pair with 2 rotis to make it a full meal.'),
R('rotis-sabzi','2 rotis with sabzi','breakfast','veg','Indian','2 rotis + veg',[8,40,5,280],[15,15],'Easy',1,'',
  ['60|g|atta (wheat flour)|G','150|g|mixed vegetables|P','1|tsp|oil|S','0.5|tsp|cumin seeds|S','0||salt|S'],
  ['Knead the atta with water into a soft dough. Rest 10 minutes.','Cook the vegetables with cumin, salt and a little oil until tender.','Roll the dough into 2 rotis and cook on a hot tawa, flipping until puffed.','Serve the rotis with the sabzi.'],
  'Add a bowl of curd on the side for +6g protein.'),
R('sprouts-chaat','Sprouts chaat','breakfast','veg','Indian','1 bowl (100g)',[7,19,5,120],[10,0],'Easy',1,'post',
  ['100|g|moong sprouts|L','1||small onion|P','1||tomato|P','0.5||cucumber|P','0.5||lemon|P','0.5|tsp|chaat masala|S','0||salt|S'],
  ['Steam or boil the sprouts for 3 minutes so they are easier to digest. Cool.','Chop onion, tomato and cucumber finely.','Toss everything with lemon juice, chaat masala and salt.'],
  'Add 50g crumbled paneer or a boiled egg for +7g protein.'),
R('chicken-omelette','Chicken omelette','breakfast','nonveg','Indian','2 eggs + 50g chicken',[20,1,0,220],[5,8],'Easy',2,'post',
  ['2||eggs|D','50|g|cooked chicken, shredded|M','1||small onion|P','1||green chilli|P','1|tsp|oil|S','0||salt and pepper|S'],
  ['Beat the eggs with salt and pepper.','Stir in shredded chicken, chopped onion and chilli.','Heat oil in a pan, pour in the mix, and cook on medium for 2 minutes.','Fold in half and cook 1 more minute.'],
  'Use leftover tandoori or grilled chicken for extra flavour.'),
R('masala-omelette','Masala omelette','breakfast','egg','Indian','2 eggs',[13,4,1,190],[5,5],'Easy',1,'post',
  ['2||eggs|D','1||small onion|P','1||tomato|P','1||green chilli|P','1|tbsp|coriander|P','1|tsp|oil|S','0||salt|S','0.25|tsp|turmeric|S'],
  ['Beat the eggs with salt and turmeric.','Mix in finely chopped onion, tomato, chilli and coriander.','Pour into a hot oiled pan and spread out.','Cook 2 minutes, flip, and cook 1 more minute.'],
  'Add a third egg or a slice of cheese for +6g protein.'),
R('pesarattu','Moong dal dosa (pesarattu)','breakfast','veg','Indian','2 dosas',[14,30,6,250],[10,15],'Medium',1,'',
  ['80|g|whole green moong (soaked 6 h)|L','1|inch|ginger|P','2||green chillies|P','0.5|tsp|cumin seeds|S','1|tsp|oil|S','0||salt|S'],
  ['Soak the moong for 6 hours or overnight. Drain.','Grind with ginger, chillies, cumin, salt and a little water into a thick batter.','Pour a ladle onto a hot tawa and spread thin like a dosa.','Drizzle oil around the edges and cook until crisp. Flip briefly.','Serve with coconut or tomato chutney.'],
  'Serve with a bowl of curd for +6g protein.'),
R('veg-upma','Vegetable upma','breakfast','veg','Indian','1 bowl',[6,40,4,260],[5,15],'Easy',1,'pre',
  ['50|g|rava (semolina)|G','1||small onion|P','0.5|cup|mixed vegetables|P','1|tsp|mustard seeds|S','1|tsp|urad dal|L','8||curry leaves|P','1|tsp|oil|S','0||salt|S'],
  ['Dry-roast the rava in a pan for 3 minutes until fragrant. Set aside.','Heat oil, add mustard seeds, urad dal and curry leaves.','Add onion and vegetables. Cook 4 minutes.','Pour in 180ml hot water with salt and bring to a boil.','Stir in the rava slowly and cook 2 minutes until thick.'],
  'Top with roasted peanuts or serve with a boiled egg for +5g protein.'),
R('idli-sambar','Idli with sambar','breakfast','veg','Indian','3 idlis + 1 bowl sambar',[11,52,6,300],[10,20],'Medium',1,'pre',
  ['3||idlis (ready batter)|G','40|g|toor dal|L','1||tomato|P','0.5|cup|vegetables (drumstick, carrot)|P','1|tbsp|sambar powder|S','1|tsp|tamarind paste|S','1|tsp|oil|S','0||salt|S'],
  ['Steam the idlis for 10 to 12 minutes.','Pressure-cook the dal with turmeric for 3 whistles. Mash.','Cook the vegetables and tomato in water with sambar powder, tamarind and salt.','Add the dal and simmer 5 minutes.','Temper with mustard seeds and curry leaves in oil, and pour over.'],
  'Add an extra bowl of sambar (+5g) or a glass of buttermilk.'),
R('overnight-oats','Overnight oats','breakfast','veg','Global','1 jar',[15,42,7,320],[5,0],'Easy',1,'pre',
  ['40|g|rolled oats|G','150|ml|milk|D','100|g|curd|D','1|tbsp|chia seeds|N','0.5||apple or banana|P','1|tsp|honey|S'],
  ['Mix oats, milk, curd and chia seeds in a jar.','Cover and refrigerate overnight, or at least 4 hours.','In the morning, stir and top with chopped fruit and honey.'],
  'Stir in 1 tbsp peanut butter for +4g protein.'),
R('pb-banana-toast','Peanut butter banana toast','breakfast','veg','Global','2 slices',[13,55,7,380],[5,3],'Easy',1,'pre',
  ['2||slices whole-wheat bread|G','1.5|tbsp|peanut butter|N','1||banana|P','0||cinnamon|S'],
  ['Toast the bread.','Spread the peanut butter evenly.','Top with banana slices and a pinch of cinnamon.'],
  'Have it with a glass of milk for +8g protein.'),
R('egg-bhurji-toast','Egg bhurji toast','breakfast','egg','Global','2 eggs + 2 slices',[17,28,4,330],[5,7],'Easy',1,'post',
  ['2||eggs|D','2||slices whole-wheat bread|G','1||small onion|P','1||tomato|P','1|tsp|oil|S','0||salt|S','0.25|tsp|turmeric|S'],
  ['Cook chopped onion in oil for 2 minutes, then add tomato.','Crack in the eggs with salt and turmeric.','Scramble on low heat until just set.','Pile onto toasted bread.'],
  'Add 1 extra egg white to the scramble for +4g protein.'),
R('paneer-paratha','Paneer paratha','breakfast','veg','Indian','1 large paratha',[14,38,5,330],[15,10],'Medium',2,'',
  ['50|g|atta (wheat flour)|G','60|g|paneer|D','1||green chilli|P','1|tbsp|coriander|P','0.5|tsp|ajwain|S','1|tsp|ghee|S','0||salt|S'],
  ['Knead the atta with water into a soft dough. Rest 10 minutes.','Grate the paneer and mix with chilli, coriander, ajwain and salt.','Roll a disc, place the filling in the centre, fold the edges over, and roll out gently.','Cook on a hot tawa with a little ghee, about 2 minutes per side.'],
  'Serve with curd for +6g protein.'),

/* ---------------- lunch ---------------- */
R('dal-rice-sabzi','Dal, rice and sabzi','lunch','veg','Indian','1 katori dal + 1 cup rice + veg',[16,60,6,420],[10,25],'Easy',1,'',
  ['50|g|toor or moong dal|L','60|g|rice (raw)|G','150|g|seasonal vegetables|P','1|tsp|ghee|S','0.5|tsp|cumin seeds|S','0.25|tsp|turmeric|S','0||salt|S'],
  ['Pressure-cook the dal with turmeric and salt for 3 whistles.','Cook the rice separately.','Temper the dal with cumin in ghee.','Stir-fry the vegetables with a pinch of salt and spices.','Serve together.'],
  'Use 1.5 katori dal and add a bowl of curd for +9g protein.'),
R('rajma-rice','Rajma chawal','lunch','veg','Indian','1 katori rajma + 1 cup rice',[19,58,9,400],[10,40],'Medium',1,'',
  ['60|g|rajma (soaked overnight)|L','60|g|rice (raw)|G','1||onion|P','2||tomatoes|P','1|tsp|ginger-garlic paste|S','1|tsp|rajma or garam masala|S','1|tsp|oil|S','0||salt|S'],
  ['Soak the rajma overnight. Pressure-cook with salt for 6 to 7 whistles until soft.','Cook onion in oil until golden. Add ginger-garlic paste.','Add puréed tomato and masala, and cook until the oil separates.','Add the rajma with its water and simmer 10 minutes. Mash a few beans to thicken.','Serve with rice.'],
  'Add a side of curd or a glass of buttermilk.'),
R('paneer-sabzi-rotis','Paneer sabzi with 2 rotis','lunch','veg','Indian','100g paneer + 2 rotis',[22,44,5,460],[10,20],'Easy',2,'',
  ['100|g|paneer|D','60|g|atta (wheat flour)|G','1||capsicum|P','1||onion|P','1||tomato|P','1|tsp|oil|S','0.5|tsp|garam masala|S','0||salt|S'],
  ['Cube the paneer and vegetables.','Cook onion in oil, add tomato and masala, and cook until soft.','Add capsicum and paneer and toss for 3 minutes.','Make 2 rotis and serve.'],
  'Already high in protein. Add salad for fiber.'),
R('chana-rice','Chana masala with rice','lunch','veg','Indian','1 katori chana + 1 cup rice',[19,64,9,440],[10,35],'Medium',1,'',
  ['60|g|kabuli chana (soaked overnight)|L','60|g|rice (raw)|G','1||onion|P','2||tomatoes|P','1|tsp|chole masala|S','1|tsp|ginger-garlic paste|S','1|tsp|oil|S','0||salt|S'],
  ['Soak the chana overnight and pressure-cook for 5 to 6 whistles.','Fry onion, ginger-garlic, tomato and chole masala until thick.','Add chana and some cooking water. Simmer 10 minutes.','Serve with rice and onion slices.'],
  'Swap half the rice for 1 roti and add a bowl of curd.'),
R('chicken-rice-dal','Grilled chicken with rice and dal','lunch','nonveg','Indian','150g chicken + rice + dal',[42,56,4,520],[15,25],'Easy',2,'post',
  ['150|g|chicken breast|M','60|g|rice (raw)|G','30|g|moong dal|L','2|tbsp|curd|D','1|tsp|tandoori masala|S','0.5||lemon|P','1|tsp|oil|S','0||salt|S'],
  ['Marinate the chicken in curd, tandoori masala, lemon and salt for 15 minutes.','Grill or pan-sear 5 to 6 minutes per side until cooked through.','Cook the rice, and the dal with turmeric.','Serve together.'],
  'One of the highest-protein meals in the book. Ideal after training.'),
R('fish-curry-rice','Fish curry with rice','lunch','nonveg','Indian','150g fish + 1 cup rice',[34,46,2,430],[10,20],'Medium',2,'',
  ['150|g|fish (rohu, surmai or basa)|M','60|g|rice (raw)|G','1||onion|P','1||tomato|P','1|tsp|ginger-garlic paste|S','1|tsp|fish curry masala|S','1|tsp|oil|S','0||salt|S'],
  ['Rub the fish with turmeric and salt.','Cook onion, ginger-garlic and tomato with the masala.','Add 200ml water and bring to a simmer.','Slide in the fish and cook 6 to 8 minutes without stirring too much.','Serve with rice.'],
  'Choose fish over a second carb to keep it lean.'),
R('curd-rice','Curd rice','lunch','veg','Indian','1.5 cups',[10,48,2,320],[5,15],'Easy',1,'',
  ['50|g|rice (raw)|G','150|g|curd|D','1|tsp|mustard seeds|S','8||curry leaves|P','1||green chilli|P','1|tsp|oil|S','0||salt|S'],
  ['Cook the rice soft and let it cool slightly.','Mash it with curd and salt.','Temper mustard, curry leaves and chilli in oil and pour over.','Serve cool.'],
  'Mix in 2 tbsp of roasted chana dal or pomegranate for crunch.'),
R('soya-chunk-curry','Soya chunk curry with rotis','lunch','veg','Indian','50g dry soya + 2 rotis',[24,46,6,380],[10,20],'Easy',1,'post',
  ['50|g|soya chunks|L','60|g|atta (wheat flour)|G','1||onion|P','1||tomato|P','1|tsp|ginger-garlic paste|S','1|tsp|garam masala|S','1|tsp|oil|S','0||salt|S'],
  ['Boil the soya chunks for 5 minutes, then squeeze out the water.','Cook onion, ginger-garlic, tomato and masala into a gravy.','Add the soya and 150ml water. Simmer 8 minutes.','Serve with 2 rotis.'],
  'Soya is one of the cheapest high-protein foods. 50g dry gives about 26g protein.'),
R('sambar-rice','Sambar rice','lunch','veg','Indian','1 big bowl',[12,62,8,380],[10,25],'Easy',1,'',
  ['40|g|toor dal|L','60|g|rice (raw)|G','1|cup|vegetables (drumstick, brinjal, carrot)|P','1|tbsp|sambar powder|S','1|tsp|tamarind paste|S','1|tsp|ghee|S','0||salt|S'],
  ['Pressure-cook the dal and rice together with turmeric for 3 whistles.','Cook the vegetables with sambar powder, tamarind and salt.','Mix everything to a porridge-like texture.','Temper with mustard and curry leaves in ghee.'],
  'Serve with a boiled egg or a cup of curd.'),
R('egg-curry-rice','Egg curry with rice','lunch','egg','Indian','2 eggs + 1 cup rice',[17,52,3,430],[10,20],'Easy',1,'',
  ['2||eggs|D','60|g|rice (raw)|G','1||onion|P','1||tomato|P','1|tsp|ginger-garlic paste|S','1|tsp|egg curry masala|S','1|tsp|oil|S','0||salt|S'],
  ['Hard-boil the eggs, peel, and make shallow cuts on them.','Cook onion, ginger-garlic, tomato and masala into a thick gravy.','Add 150ml water and the eggs. Simmer 5 minutes.','Serve with rice.'],
  'Add a third egg for +6g protein.'),
R('chicken-biryani','Home chicken biryani (lean)','lunch','nonveg','Indian','1 plate',[30,58,3,520],[20,35],'Hard',3,'post',
  ['120|g|chicken (bone-in or breast)|M','70|g|basmati rice|G','2|tbsp|curd|D','1||onion|P','1|tsp|biryani masala|S','1|tsp|ginger-garlic paste|S','1|tsp|ghee|S','0||mint and coriander|P','0||salt|S'],
  ['Marinate the chicken in curd, biryani masala, ginger-garlic and salt for 20 minutes.','Soak the rice 20 minutes, then boil until 70% cooked. Drain.','Fry sliced onion in ghee until brown. Add the chicken and cook 10 minutes.','Layer the rice over the chicken with mint and coriander.','Cover tightly and cook on the lowest heat for 15 minutes.'],
  'Keep the rice to one cup and add raita for extra protein.'),
R('palak-paneer','Palak paneer with rotis','lunch','veg','Indian','100g paneer + 2 rotis',[21,40,6,450],[15,20],'Medium',2,'',
  ['100|g|paneer|D','200|g|spinach|P','60|g|atta (wheat flour)|G','1||onion|P','1||tomato|P','1|tsp|ginger-garlic paste|S','1|tsp|oil|S','0||salt|S'],
  ['Blanch the spinach for 2 minutes, cool, and blend to a purée.','Cook onion, ginger-garlic and tomato until soft.','Add the spinach purée and salt. Simmer 5 minutes.','Add paneer cubes and cook 2 minutes. Serve with rotis.'],
  'Spinach adds iron. Add a squeeze of lemon to help absorb it.'),
R('chicken-wrap','Chicken wrap','lunch','nonveg','Global','1 large wrap',[30,38,4,400],[10,10],'Easy',2,'post',
  ['100|g|chicken breast|M','1||whole-wheat tortilla or roti|G','2|tbsp|hung curd|D','0.5||onion|P','1||tomato|P','1|cup|lettuce or cabbage|P','1|tsp|oil|S','0||salt, pepper, paprika|S'],
  ['Slice the chicken thin and season with salt, pepper and paprika.','Pan-sear in oil for 6 to 7 minutes until cooked.','Warm the tortilla and spread hung curd on it.','Add vegetables and chicken, then roll tightly.'],
  'Use hung curd with garlic as a high-protein sauce instead of mayo.'),
R('paneer-rice-bowl','Paneer rice bowl','lunch','veg','Global','1 bowl',[22,50,5,450],[10,15],'Easy',2,'',
  ['100|g|paneer|D','60|g|rice (raw)|G','1||capsicum|P','0.5|cup|corn or peas|P','1|tbsp|soy sauce|S','1|tsp|oil|S','0||chilli flakes|S'],
  ['Cook the rice.','Sear paneer cubes in oil until golden.','Add capsicum and corn, then soy sauce and chilli flakes. Toss 2 minutes.','Serve over the rice.'],
  'Swap half the paneer for tofu for a lighter version with the same protein.'),

/* ---------------- snacks ---------------- */
R('roasted-chana','Roasted chana','snack','veg','Indian','1 handful (30g)',[6,15,5,100],[0,0],'Easy',1,'',
  ['30|g|roasted chana|L'],['Eat as is, or toss with chaat masala and lemon.'],'Pair with a glass of buttermilk.'),
R('peanuts','Peanuts','snack','veg','Indian','1 handful (30g)',[8,6,3,170],[0,5],'Easy',1,'',
  ['30|g|peanuts|N','0||salt|S'],['Dry-roast in a pan for 4 to 5 minutes, stirring.','Cool and sprinkle with a pinch of salt.'],'High in calories, so stick to one handful.'),
R('banana','Banana','snack','veg','Indian','1 medium',[1,23,3,90],[0,0],'Easy',1,'pre',
  ['1||banana|P'],['Eat 30 to 45 minutes before training for quick energy.'],'Add a spoon of peanut butter for +4g protein.'),
R('apple','Apple','snack','veg','Indian','1 medium',[0,25,4,95],[0,0],'Easy',1,'pre',
  ['1||apple|P'],['Wash and slice.'],'Pair with 10 almonds for protein and healthy fat.'),
R('buttermilk','Masala buttermilk','snack','veg','Indian','1 glass (250ml)',[3,5,0,40],[3,0],'Easy',1,'',
  ['100|g|curd|D','150|ml|water|S','0.5|tsp|roasted cumin powder|S','0||salt|S','0||mint or coriander|P'],
  ['Whisk curd and water until smooth.','Add cumin, salt and chopped mint.','Serve chilled.'],'Great after training on hot days for fluids and salt.'),
R('boiled-egg','Boiled egg','snack','egg','Indian','1 egg',[6,0,0,70],[1,10],'Easy',1,'post',
  ['1||egg|D','0||salt and pepper|S'],['Boil 9 to 10 minutes, cool in water, peel, and season.'],'Boil a batch for the week. They keep 5 days in the fridge.'),
R('milk','Glass of milk','snack','veg','Indian','1 glass (250ml)',[8,12,0,150],[0,3],'Easy',1,'post',
  ['250|ml|milk|D','0||turmeric or cardamom|S'],['Warm the milk, and add a pinch of turmeric or cardamom if you like.'],'Blend with a banana for a quick post-workout shake.'),
R('almonds','Almonds','snack','veg','Indian','10 pieces',[3,2,2,70],[0,0],'Easy',2,'',
  ['10||almonds|N'],['Soak overnight if you prefer them softer.'],'Combine with a glass of milk for a better protein snack.'),
R('sattu-drink','Sattu drink','snack','veg','Indian','1 glass (60g sattu)',[12,20,11,220],[3,0],'Easy',1,'post',
  ['60|g|sattu (roasted gram flour)|L','300|ml|water|S','0.5||lemon|P','0.5|tsp|roasted cumin powder|S','0||salt|S'],
  ['Whisk the sattu into the water until there are no lumps.','Add lemon juice, cumin and salt.','Stir well and drink immediately.'],'An old-school Bihari protein drink. Cheap and filling.'),
R('hung-curd-bowl','Hung curd bowl','snack','veg','Global','150g hung curd',[12,10,1,150],[5,0],'Easy',1,'post',
  ['250|g|curd (strained for 1 hour)|D','0.5||apple or berries|P','1|tsp|honey|S','1|tsp|chia or flax seeds|N'],
  ['Strain the curd in a muslin cloth or sieve for 1 hour in the fridge.','Spoon into a bowl.','Top with fruit, honey and seeds.'],'Hung curd is India\'s Greek yoghurt: about twice the protein of regular curd.'),
R('banana-pb-smoothie','Banana peanut smoothie','snack','veg','Global','1 large glass',[14,40,4,330],[5,0],'Easy',1,'post',
  ['250|ml|milk|D','1||banana|P','1|tbsp|peanut butter|N','1|tbsp|oats|G'],
  ['Add everything to a blender.','Blend for 30 seconds until smooth.','Drink within 30 minutes of training.'],'Use curd instead of half the milk for a thicker, higher-protein shake.'),
R('roasted-makhana','Roasted makhana','snack','veg','Indian','1 bowl (25g)',[4,20,3,110],[0,6],'Easy',2,'pre',
  ['25|g|makhana (fox nuts)|N','1|tsp|ghee|S','0||salt, pepper, chaat masala|S'],
  ['Heat ghee in a pan on low heat.','Add the makhana and roast, stirring, for 5 to 6 minutes until crisp.','Season and cool.'],'Light enough to eat before training.'),
R('egg-sandwich','Egg sandwich','snack','egg','Global','1 sandwich',[15,28,3,290],[5,10],'Easy',1,'post',
  ['2||eggs|D','2||slices whole-wheat bread|G','1|tbsp|hung curd|D','0.5||cucumber|P','0||salt and pepper|S'],
  ['Boil the eggs, peel, and chop.','Mix with hung curd, salt and pepper.','Spread on bread with cucumber slices.','Toast or eat as is.'],'Hung curd instead of mayo keeps it high-protein and light.'),
R('chana-chaat','Chana chaat','snack','veg','Indian','1 bowl',[10,30,8,220],[10,0],'Easy',1,'',
  ['100|g|boiled kabuli chana|L','1||small onion|P','1||tomato|P','0.5||lemon|P','0.5|tsp|chaat masala|S','0||coriander|P','0||salt|S'],
  ['Mix the boiled chana with chopped onion and tomato.','Add lemon juice, chaat masala, salt and coriander.','Toss and eat fresh.'],'Add a spoon of curd and some sprouts to stretch the protein.'),

/* ---------------- dinner ---------------- */
R('dal-rotis-sabzi','Dal, 2 rotis and sabzi','dinner','veg','Indian','1 katori dal + 2 rotis + veg',[14,48,7,380],[10,25],'Easy',1,'',
  ['50|g|moong or masoor dal|L','60|g|atta (wheat flour)|G','150|g|seasonal vegetables|P','1|tsp|ghee|S','0.5|tsp|cumin seeds|S','0||salt|S'],
  ['Pressure-cook the dal with turmeric for 3 whistles. Temper with cumin in ghee.','Cook the vegetables with a little oil and spices.','Make 2 rotis.','Serve together.'],
  'Use a thicker dal (1.5 katori) or add curd on the side.'),
R('chicken-salad','Grilled chicken salad','dinner','nonveg','Global','150g chicken + salad',[35,8,3,280],[10,15],'Easy',2,'post',
  ['150|g|chicken breast|M','1|cup|lettuce or cabbage|P','1||cucumber|P','1||tomato|P','0.5||lemon|P','1|tsp|olive or mustard oil|S','0||salt, pepper, oregano|S'],
  ['Season the chicken with salt, pepper and oregano.','Grill or pan-sear 5 to 6 minutes per side. Rest, then slice.','Chop the vegetables.','Toss with lemon, oil and salt, and top with the chicken.'],
  'Light, high-protein dinner. Add a roti if you trained hard.'),
R('paneer-tikka','Paneer tikka with roti','dinner','veg','Indian','100g paneer + 2 rotis',[22,36,5,410],[20,15],'Medium',2,'',
  ['100|g|paneer|D','2|tbsp|curd|D','1||capsicum|P','1||onion|P','1|tsp|tikka masala|S','60|g|atta (wheat flour)|G','1|tsp|oil|S','0||salt|S'],
  ['Mix curd, tikka masala and salt. Coat the paneer and vegetable cubes. Rest 15 minutes.','Thread onto skewers or spread on a tray.','Grill or pan-cook on high heat until charred, about 8 minutes.','Serve with 2 rotis and onion rings.'],
  'Curd in the marinade adds protein and keeps the paneer soft.'),
R('khichdi','Moong dal khichdi','dinner','veg','Indian','1.5 bowls',[11,52,4,340],[5,20],'Easy',1,'',
  ['40|g|moong dal|L','40|g|rice|G','0.5|cup|vegetables (optional)|P','1|tsp|ghee|S','0.5|tsp|cumin seeds|S','0.25|tsp|turmeric|S','0||salt|S'],
  ['Wash the dal and rice together.','Pressure-cook with 3 cups water, turmeric, salt and vegetables for 4 whistles.','Temper cumin in ghee and pour over.','Serve with curd.'],
  'Use 60g dal and 20g rice for a higher-protein khichdi.'),
R('egg-curry-roti','Egg curry with 2 rotis','dinner','egg','Indian','2 eggs + 2 rotis',[18,36,4,360],[10,20],'Easy',1,'',
  ['2||eggs|D','60|g|atta (wheat flour)|G','1||onion|P','1||tomato|P','1|tsp|ginger-garlic paste|S','1|tsp|garam masala|S','1|tsp|oil|S','0||salt|S'],
  ['Hard-boil and peel the eggs.','Cook onion, ginger-garlic, tomato and masala into a gravy.','Add the eggs and a splash of water. Simmer 5 minutes.','Serve with 2 rotis.'],
  'Add a third egg for +6g protein.'),
R('veg-soup-salad','Vegetable soup with salad','dinner','veg','Global','1 bowl + salad',[5,18,6,150],[10,15],'Easy',1,'',
  ['2|cups|mixed vegetables|P','1||tomato|P','1|tsp|butter or oil|S','0||salt and pepper|S','1||cucumber|P'],
  ['Chop the vegetables small.','Cook in butter for 2 minutes, then add 400ml water and salt.','Simmer 12 minutes, then blend partly if you like.','Season with pepper and serve with cucumber salad.'],
  'Too low in protein on its own. Add paneer cubes or a boiled egg.'),
R('moong-cheela-curd','Moong dal cheela with curd','dinner','veg','Indian','2 pieces + 100g curd',[16,26,5,280],[10,10],'Easy',1,'',
  ['60|g|yellow moong dal (soaked 3 h)|L','100|g|curd|D','1||green chilli|P','1|inch|ginger|P','1|tsp|oil|S','0||salt|S'],
  ['Soak the dal 3 hours, then grind with chilli, ginger and salt into a batter.','Spread thin on a hot tawa with a little oil.','Cook 2 minutes per side.','Serve with curd.'],
  'Stuff with grated paneer for +7g protein.'),
R('fish-steamed-veg','Fish with steamed veg','dinner','nonveg','Global','150g fish + veg',[32,10,4,260],[10,15],'Easy',2,'post',
  ['150|g|fish fillet|M','1|cup|broccoli, beans or carrot|P','0.5||lemon|P','1|tsp|oil|S','0||salt, pepper, garlic|S'],
  ['Season the fish with salt, pepper, garlic and lemon.','Pan-sear in oil for 3 to 4 minutes per side.','Steam the vegetables for 5 minutes.','Serve together with lemon.'],
  'Very lean. Add a roti or some rice if you trained hard.'),
R('chicken-curry-rotis','Chicken curry with rotis','dinner','nonveg','Indian','150g chicken + 2 rotis',[32,38,4,460],[15,25],'Medium',2,'post',
  ['150|g|chicken|M','60|g|atta (wheat flour)|G','1||onion|P','2||tomatoes|P','1|tsp|ginger-garlic paste|S','1|tsp|chicken masala|S','1|tsp|oil|S','0||salt|S'],
  ['Cook onion in oil until golden. Add ginger-garlic paste.','Add tomato and masala, and cook until the oil separates.','Add the chicken and salt. Cook covered for 15 to 18 minutes.','Serve with 2 rotis.'],
  'Choose breast meat for the leanest version.'),
R('soya-keema','Soya keema with roti','dinner','veg','Indian','50g dry soya + 2 rotis',[26,36,7,380],[10,15],'Easy',1,'post',
  ['50|g|soya granules|L','60|g|atta (wheat flour)|G','1||onion|P','1||tomato|P','0.5|cup|peas|P','1|tsp|garam masala|S','1|tsp|oil|S','0||salt|S'],
  ['Soak the soya granules in hot water for 10 minutes. Squeeze dry.','Cook onion, tomato and masala.','Add soya and peas, and cook 6 minutes.','Serve with 2 rotis.'],
  'Tastes like mutton keema at a fraction of the cost and fat.'),
R('dal-palak-rice','Dal palak with rice','dinner','veg','Indian','1 bowl + 1 cup rice',[15,50,8,380],[10,25],'Easy',1,'',
  ['50|g|toor or moong dal|L','100|g|spinach|P','60|g|rice (raw)|G','1||tomato|P','1|tsp|ghee|S','0.5|tsp|cumin seeds|S','0||salt|S'],
  ['Pressure-cook the dal with turmeric for 3 whistles.','Add chopped spinach and tomato and simmer 5 minutes.','Temper with cumin and garlic in ghee.','Serve with rice.'],
  'Add a squeeze of lemon to help absorb the iron.'),
R('egg-fried-rice','Egg fried rice','dinner','egg','Global','1 plate',[16,55,3,420],[10,10],'Easy',1,'',
  ['2||eggs|D','60|g|rice (cooked the day before)|G','0.5|cup|mixed vegetables|P','1||spring onion|P','1|tbsp|soy sauce|S','1|tsp|oil|S','0||pepper|S'],
  ['Scramble the eggs in oil and set aside.','Stir-fry the vegetables on high heat for 2 minutes.','Add the cold rice, soy sauce and pepper. Toss 3 minutes.','Fold the eggs back in and top with spring onion.'],
  'Day-old rice fries best. Add a third egg for +6g protein.'),
R('paneer-stir-fry','Paneer stir-fry','dinner','veg','Global','100g paneer + veg',[20,12,3,300],[10,10],'Easy',2,'',
  ['100|g|paneer|D','1||capsicum|P','0.5||onion|P','0.5|cup|broccoli or beans|P','1|tbsp|soy sauce|S','1|tsp|oil|S','0||garlic and chilli flakes|S'],
  ['Cut the paneer and vegetables into strips.','Sear the paneer in a hot pan until golden. Remove.','Stir-fry garlic and vegetables for 3 minutes on high heat.','Add the paneer and soy sauce and toss for 1 minute.'],
  'Low-carb dinner. Add a roti if you trained hard.')
];
const RECIPE_BY_ID=Object.fromEntries(RECIPES.map(r=>[r.id,r]));
const MEAL_ORDER=['breakfast','lunch','snack','dinner'];
const MEAL_LABEL={breakfast:'Breakfast',lunch:'Lunch',snack:'Snacks',dinner:'Dinner'};
